<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>KurrentDB.Embedded.Sample</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Serilog.Sinks.Console" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\KurrentDB.Embedded\KurrentDB.Embedded.csproj" />
	</ItemGroup>
</Project>
