### Create Logger Sink Connector
POST localhost:2113/connectors/create
Content-Type: application/json

{
  "connectorId": "demo-logger-sink",
  "name": "Demo Logger Sink",
  "settings": {
    "InstanceTypeName": "EventStore.Connectors.Testing.LoggerSink",
    "Subscription:Filter:Scope": "Stream",
    "Subscription:Filter:Expression": "^\\$connectors\\/[^\\/]+\\/leases",
    "Subscription:InitialPosition": "Earliest"
  }
}

### Start Logger Sink Connector
POST localhost:2113/connectors/start
Content-Type: application/json

{
  "connectorId": "demo-logger-sink"
}

### Start Logger Sink Connector from a specific position
POST localhost:2113/connectors/start
Content-Type: application/json

{
  "connectorId": "demo-logger-sink",
  "startPosition": {
    "value": "99"
  }
}

### Stop Logger Sink Connector
POST localhost:2113/connectors/stop
Content-Type: application/json

{
  "connectorId": "demo-logger-sink"
}

### Delete Logger Sink Connector
POST localhost:2113/connectors/delete
Content-Type: application/json

{
  "connectorId": "demo-logger-sink"
}

### Create HTTP Sink Connector
POST localhost:2113/connectors/create
Content-Type: application/json

{
  "connectorId": "demo-http-sink",
  "name": "Demo Http Sink",
  "settings": {
    "InstanceTypeName": "EventStore.Connectors.Http.HttpSink",
    "Url": "http://localhost:8080",
    "Subscription:Filter:Scope": "Stream",
    "Subscription:Filter:Expression": "^\\$connectors\\/[^\\/]+\\/leases",
    "Subscription:InitialPosition": "Earliest",
  }
}

### Start HTTP Sink Connector
POST localhost:2113/connectors/start
Content-Type: application/json

{
  "connectorId": "demo-http-sink"
}

### Start HTTP Sink Connector from a specific position
POST localhost:2113/connectors/start
Content-Type: application/json

{
  "connectorId": "demo-http-sink",
  "startPosition": {
    "value": "99"
  }
}

### Stop HTTP Sink Connector
POST localhost:2113/connectors/stop
Content-Type: application/json

{
  "connectorId": "demo-http-sink"
}

### Delete HTTP Sink Connector
POST localhost:2113/connectors/delete
Content-Type: application/json

{
  "connectorId": "demo-http-sink"
}

<> 2024-07-29T185430.400.json
<> 2024-07-29T185344.200.json

### Rename HTTP Sink Connector
POST localhost:2113/connectors/rename
Content-Type: application/json

{
  "connectorId": "demo-http-sink",
  "name": "Renamed Demo Http Sink"
}

### Create Logger Sink Connector
POST localhost:2113/connectors/create
Content-Type: application/json

{
  "connectorId": "logger-sink-connector-1",
  "name": "logger-sink-connector-1",
  "settings": {
    "instanceTypeName": "EventStore.Connect.Connectors.LoggerSink"
  }
}