@WebApplicationAOT_HostAddress = http://localhost:20000

GET {{WebApplicationAOT_HostAddress}}/todos/
Accept: application/json

###

GET {{WebApplicationAOT_HostAddress}}/todos/1
Accept: application/json

###
