<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<GitVersion>false</GitVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsTrimmable>true</IsTrimmable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Kurrent.Quack" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Serilog" />
	</ItemGroup>

</Project>
