// autogenerated
using System.Threading;

#pragma warning disable CS0108 // Member hides inherited member; missing new keyword
namespace KurrentDB.SourceGenerators.Tests.Messaging.NestedDerived
{
	partial class B
	{
		private partial class A
		{
			public static string OriginalLabelStatic { get; } = "TestMessageGroup-NestedDerived-A";

			private static string _labelStatic;
			public static string LabelStatic { get => _labelStatic ??= ResolveLabel(OriginalLabelStatic); set => _labelStatic = value; }
			public override string Label => LabelStatic;
		}

		public static string OriginalLabelStatic { get; } = "TestMessageGroup-NestedDerived-B";

		private static string _labelStatic;
		public static string LabelStatic { get => _labelStatic ??= ResolveLabel(OriginalLabelStatic); set => _labelStatic = value; }
		public override string Label => LabelStatic;
	}
}
