// autogenerated
using System.Threading;

#pragma warning disable CS0108 // Member hides inherited member; missing new keyword
namespace KurrentDB.SourceGenerators.Tests.Messaging.Simple
{
	public partial class A
	{
		public static string OriginalLabelStatic { get; } = "TestMessageGroup-Simple-A";

		private static string _labelStatic;
		public static string LabelStatic { get => _labelStatic ??= ResolveLabel(OriginalLabelStatic); set => _labelStatic = value; }
		public override string Label => LabelStatic;
	}

	public partial class B
	{
		public static string OriginalLabelStatic { get; } = "TestMessageGroup-Simple-B";

		private static string _labelStatic;
		public static string LabelStatic { get => _labelStatic ??= ResolveLabel(OriginalLabelStatic); set => _labelStatic = value; }
		public override string Label => LabelStatic;
	}
}
