name: Build - Reusable

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      cs_symbols:
        required: false
        type: string
        default: ""

jobs:
# todo, consider matrix of slnf files to group assemblies together. each job could run a separate slnf.
# this may be more practical after githubactionstestrunner supports MTP, making failures easier to understand at a glance.
  discover_projects:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.discover.outputs.modules }}
    steps:
      - uses: actions/checkout@v4
      - id: discover
        run: |
          find src -maxdepth 3 -name "*.Tests.csproj" > projects.txt
          echo "src/KurrentDB/KurrentDB.csproj" >> projects.txt
          modules=$(cat projects.txt | jq -R . | jq -sc .)
          echo "modules=$modules" >> $GITHUB_OUTPUT
  build:
    needs: discover_projects
    env:
      DB_IMAGE: kurrentdb-test-container
    strategy:
      fail-fast: false
      matrix:
        configuration: [release]
        module: ${{ fromJson(needs.discover_projects.outputs.modules) }}
    runs-on: ${{ inputs.os }}
    name: ${{ matrix.module }}
    steps:
    -  
      name: Install Azure Emulator
      if: ${{ contains(inputs.cs_symbols, 'RUN_AZ_TESTS') }}
      run: |
        npm install -g azurite
        azurite --location /tmp/azurite &
        curl -I http://127.0.0.1:10000/ --retry 5 --retry-delay 1 --retry-connrefused
#    -  
#      name: Free Disk Space (Ubuntu)
#      if: ${{ !startsWith(inputs.os, 'windows') }}
#      uses: jlumbroso/free-disk-space@v1.3.1
#      with:
#        tool-cache: false
#        dotnet: false
#        docker-images: false
    -  
      name: Checkout
      uses: actions/checkout@v4
    -  
      name: Set up Docker Buildx
      if: ${{ !startsWith(inputs.os, 'windows') }}
      uses: docker/setup-buildx-action@v2
    -  
      name: Install net10.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 10.0.x
    # //qq check this
    -
      name: Use nuget cache
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          nuget-${{ runner.os }}-
    -  
      name: Clear Nuget Config
      shell: powershell
      if: ${{ startsWith(inputs.os, 'windows') }}
      run: |
        if (-not(Test-Path $env:APPDATA\NuGet\NuGet.Config -PathType Leaf)) {
          return;
        }
        Remove-Item $env:APPDATA\NuGet\NuGet.Config
    -  
      name: Compile
      shell: bash
      run: >
        dotnet build
        --configuration ${{ matrix.configuration }}
        -p:DefineConstants=${{ inputs.cs_symbols }}
        ${{ matrix.module }}
    -  
      name: Verify Build
      if: ${{ matrix.module == 'src/KurrentDB/KurrentDB.csproj' }}
      shell: bash
      run: |
        dotnet run --project ${{ matrix.module }} --configuration ${{ matrix.configuration }} -- --insecure --what-if
    # so that the oauth tests have an up to date server image to run against
    -  
      name: Build Test Image
      if: ${{ matrix.module == 'src/KurrentDB/KurrentDB.csproj' && !startsWith(inputs.os, 'windows') }}
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        target: runtime
        tags: ${{ env.DB_IMAGE }}
    -  
      name: Run Tests
      if: ${{ endsWith(matrix.module, '.Tests.csproj') }}
      shell: bash
      run: >
        dotnet test
        --results-directory $(pwd)/test-results
        --no-build
        --configuration ${{ matrix.configuration }}
        --project ${{ matrix.module }}
    -
      name: Remove slashes
      if: ${{ endsWith(matrix.module, '.Tests.csproj') }}
      id: remove_slashes
      shell: bash
      run: |
        base="${{ matrix.module }}"
        safe="${base//\//-}"
        echo "value=$safe" >> $GITHUB_OUTPUT
    -  
      name: Publish Test Results (All)
      uses: actions/upload-artifact@v4
      if: ${{ endsWith(matrix.module, '.Tests.csproj') }}
      with:
        name: test-results-${{ steps.remove_slashes.outputs.value }}
        path: |
          test-results/*.trx
