name: Deployment Tests

on:
  workflow_dispatch:
    inputs:
      kdb_version:
        required: true
        description: "KurrentDB version"
        type: string

jobs:
  install-deb-package:
    name: Verify DEB package on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Download DEB package
        run: |
          DEB_URL="https://packages.kurrent.io/public/kurrent-latest/deb/any-distro/pool/any-version/main/k/ku/kurrentdb_{{$github.event.inputs.kdb_version}}/kurrentdb-{{$github.event.inputs.kdb_version}}-linux.x64-debian.deb"
          curl -L -o package.deb "$DEB_URL"

      - name: Install DEB package
        run: |
          sudo dpkg -i package.deb || sudo apt-get install -f -y

      - name: Verify package installation
        run: |
          PACKAGE_NAME="kurrendb"
          if dpkg -s "$PACKAGE_NAME" >/dev/null 2>&1; then
            echo "Package $PACKAGE_NAME is installed."
          else
            echo "Package $PACKAGE_NAME is NOT installed."
            exit 1
          fi
